#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# Setup DWM:
# Set resolution with refresh-rate
xrandr --output eDP-1 --mode 1920x1080 --rate 60

# Set brightness to 50%
xrandr --output eDP-1 --brightness 0.5 &

# Set wallpaper and the theme
"$HOME/.local/bin/newlook" &

# Start compositer
xcompmgr &

# Start notification manager
dunst &

# Set stauts bar and watch_bt
"$HOME/.local/bin/status-bar.sh" &

# Start hotkey manager
sxhkd -c "$HOME/.config/sxhkd/sxhkdrc" &

# Start DWM
exec dwm
